config/routes.rb
get 'budget', to: 'budget#index', as: :budget
get 'budget/calculate', to: 'budget#calculate', as: :budget_calculate
get 'budget/issues', to: 'budget#issues', as: :budget_issues

post 'issues/:issue_id/additional_cost', to: 'additional_costs#create', as: :additional_cost
delete 'issues/:issue_id/additional_cost/:id', to: 'additional_costs#destroy', as: :additional_cost

app/models/additional_cost.rb
class AdditionalCost < ActiveRecord::Base
  unloadable

  attr_accessible :name, :cost, :issue_id

  validates :name, presence: true
  validates :cost, presence: true, numericality: true

  belongs_to :issue
end

app/controllers/additional_costs_controller.rb
class AdditionalCostsController < ApplicationController
  unloadable

  def create
    @issue = Issue.find(params[:issue_id])
    @cost = @issue.additional_costs.build(params[:additional_cost])

    if @cost.save
      render partial: 'additional_costs/cost', locals: { cost: @cost }
    end
  end

  def destroy
    @cost = AdditionalCost.find(params[:id])
    if @cost.destroy
      render text: 'ok'
    end
  end
end

app/controllers/budget_controller.rb
include ActionView::Helpers::TextHelper

class BudgetController < ApplicationController
  unloadable

  # skip_before_filter :check_if_login_required
  # skip_before_filter :verify_authenticity_token

  # accept_api_auth :check_for_new_deals

  before_filter :find_settings, only: [:index, :issues, :calculate]

  def index
    @issue = Issue.find(params[:issue_id]) if params[:issue_id].present?
  end

  def issues
    @issues = Issue.where(tracker_id: @settings[:tracker_id] || 5)
    exclude_issues
    apply_filter if view_context.filter_options.include? params[:filter_option]
  end

  def calculate
    @result = {}

    cost_factor = @settings[:cost_factor].to_f
    rate_factor = @settings[:rate_factor].to_f
    base_rate = params.key?(:rate) ? params[:rate].to_f : @settings[:default_rate].to_f

    rate = (base_rate * rate_factor).ceil
    work_cost = (base_rate * cost_factor).ceil

    # profit_share = @settings[:profit_share].to_f
    # provision = @settings[:provision].to_f

    case params[:type]
    when 'rate'
      @result = {
        rate: rate,
        work_cost: work_cost
      }
    when 'budget'
      count_estimate_budget(cost_factor, rate_factor)
    end

    respond_to do |format|
      format.html { render layout: false }
      format.json { render json: @result }
    end
  end

  private

  def find_settings
    @settings ||= Setting[:plugin_redmine_budget]
  end

  def apply_filter
    case params[:filter_option]
    when 'Project'
      @issues = @issues.where(project_id: params[:filter_value])
    when 'Category'
      @issues = @issues.where(category_id: params[:filter_value])
    when 'Assignee'
      @issues = @issues.where(assigned_to_id: params[:filter_value])
    end
  end

  def exclude_issues
    @issues = @issues.open
    unless User.current.can_manage_budget?
      @issues = @issues.where(assigned_to_id: User.current.id)
    end
  end

  def count_estimate_budget(cost_factor, rate_factor)
    @result = []

    params[:estimation].each do |row|
      hours = row[:hours].to_f
      base_rate = row[:rate].to_f

      total_work_cost = ((hours * cost_factor) * base_rate).ceil
      middle_bid = ((hours * rate_factor) * base_rate).ceil
      lower_bid = (middle_bid * (1.0 - @settings[:margin].to_f)).ceil
      upper_bid = (middle_bid * (1.0 + @settings[:margin].to_f)).ceil

      @result << {
        work_cost: total_work_cost,
        lower_bid: lower_bid,
        middle_bid: middle_bid,
        upper_bid: upper_bid
      }
    end

    additional_cost = params[:additionals].sum { |row| row[:cost].to_f }

    @result << {
      total_work_cost: @result.sum { |row| row[:work_cost] } + additional_cost,
      total_lower_bid: @result.sum { |row| row[:lower_bid] } + additional_cost,
      total_middle_bid: @result.sum { |row| row[:middle_bid] } + additional_cost,
      total_upper_bid: @result.sum { |row| row[:upper_bid] } + additional_cost
    }
  end
end

app/helpers/additional_costs_helper.rb
module AdditionalCostsHelper
end

app/helpers/budget_helper.rb
module BudgetHelper
  def issue_link(issue)
    "##{issue.id} #{issue.subject}"
  end

  def filter_options
    arr = ['Project']
    arr << 'Assignee' if User.current.can_manage_budget?
    arr
  end

  def filter_values(op)
    return nil unless %w(Project User).include? op
    op.constantize.all.inject([]) { |a, e| a << [e.name, e.id] }
  end
end

app/views/additional_costs/_cost.html.erb
<div class="single-cost">
  <div class="cost-name" data-cost-id="<%= cost.id %>"><%= text_field_tag :cost_name, cost.name, disabled: true %></div>
  <div class="cost-cost"><%= text_field_tag :cost_cost, cost.cost, disabled: true %></div>
  <div class="cost-del"><%= link_to "<span class='icon icon-del fa fa-times'></span>".html_safe, 'javascript: void(0);', class: 'del-cost' %></div>
  <br />
</div>

app/views/additional_costs/_form.html.erb
<div id="additional-costs-form">
  <%= text_field_tag 'additional_cost[name]', '', placeholder: t('.name') %>
  <%= text_field_tag 'additional_cost[cost]', '', placeholder: t('.cost') %>
  <%= link_to 'javascript: void(0);', id: 'add-new-cost' do %>
    <span class='icon icon-add fa fa-plus-circle'></span>
  <% end %>
</div>

app/views/additional_costs/_new.html.erb
<% if @issue.persisted? && @issue.budget? %>
  <hr />
  <div class="issue-additional-costs" data-issue-id="<%= @issue.id %>">
    <h2>Additional costs</h2>
    <% @issue.additional_costs.each do |cost| %>
      <%= render partial: 'additional_costs/cost', locals: { cost: cost } %>
    <% end %>

    <%= render partial: 'additional_costs/form' %>
  </div>
<% end %>

<% content_for :header_tags do %>
  <%= javascript_include_tag 'additional_costs', plugin: 'redmine_budget' %>
  <%= stylesheet_link_tag 'additional_costs', plugin: 'redmine_budget' %>
<% end %>

app/views/additional_costs/_show.html.erb
<% if @issue.persisted? && @issue.budget? && @issue.additional_costs.any? %>
  <hr />
  <div class="issue-additional-costs" data-issue-id="<%= @issue.id %>">
    <h2>Additional costs</h2>
    <% @issue.additional_costs.each do |cost| %>
      <%= render partial: 'additional_costs/cost', locals: { cost: cost } %>
    <% end %>
  </div>
<% end %>

<% content_for :header_tags do %>
  <%= javascript_include_tag 'additional_costs', plugin: 'redmine_budget' %>
  <%= stylesheet_link_tag 'additional_costs', plugin: 'redmine_budget' %>
<% end %>

app/views/budget/_budget.html.erb
<% if issue.budget? %>
  <style type="text/css">
    table.list td {
      border-top: 1px solid #e6eaef;
    }
  </style>

  <%= render partial: 'additional_costs/show' %>

  <% if issue.budget %>
    <h2><%= t('.summary') %></h2>
    <h3><%= t('.log_time') %></h3>

    <table class="list">
      <thead>
        <tr>
          <th><%= t('.user') %></th>
          <th><%= t('.avg_rate') %></th>
          <th><%= t('.time_sum') %></th>
          <th><%= t('.cost_sum') %></th>
        </tr>
      </thead>
      <tbody>
        <% @issue.time_entries_with_children.group_by(&:user_id).each do |user_id, time_entries| %>
          <tr>
            <td style="font-weight: bold;"><%= User.find(user_id).lastname %></td>
            <% @issue.count_costs(user_id, time_entries).each do |cost| %>
              <%= content_tag :td, cost %>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <h3><%= t('.realized') %></h3>
    <table class="list">
      <tr>
        <th><%= t('.est_time') %></th>
        <td><%= issue.estimated_hours.to_f.round(2) %></td>
      </tr>
      <tr>
        <th><%= t('.spent_time') %></th>
        <td><%= issue.spent_time.to_f.round(2) %></td>
      </tr>
      <tr>
        <th><%= t('.budget') %></th>
        <td><%= issue.budget %></td>
      </tr>
      <tr>
        <th><%= t('.profit') %></th>
        <td><%= issue.budget_profit %></td>
      </tr>
      <tr>
        <th><%= t('.provision') %></th>
        <td><%= issue.provision %></td>
      </tr>
    </table>
  <% else %>
    <p><%= t('.disclaimer', id: params[:issue_id]) %></p>
  <% end %>
  <hr />
<% end %>

app/views/budget/_filter.html.erb
<div id="manage-display">
  <%= form_tag budget_issues_path, id: 'budget-query-form', method: :get do %>
    <div id="filter-options" class="filter-part">
      <div class="label-wrapper">
        <%= label_tag 'filter_option', t('budget.issues.filter_option') %>
      </div>
      <div class="select-wrapper">
        <%= select_tag 'filter_option', options_for_select(filter_options) %>
      </div>
    </div>
    <div id="filter-project" class="filter-values filter-part">
      <div class="label-wrapper">
        <%= label_tag 'filter_value', t('budget.issues.filter_value') %>
      </div>
      <div class="select-wrapper">
        <%= select_tag 'filter_value', options_for_select(filter_values('Project')) %>
      </div>
    </div>
    <% if User.current.can_manage_budget? %>
      <div id="filter-assignee" class="filter-values filter-part" style="display: none;">
        <div class="label-wrapper">
          <%= label_tag 'filter_value', t('budget.issues.filter_value') %>
        </div>
        <div class="select-wrapper">
          <%= select_tag 'filter_value', options_for_select(filter_values('User')) %>
        </div>
      </div>
    <% end %>
    <div id="filter-button" class="filter-part">
      <%= submit_tag t('budget.issues.filter') %>
    </div>
  <% end %>

  <%= button_to t('budget.issues.show_all'), budget_issues_path, method: :get %>
</div>

app/views/budget/_head.html.erb
<% content_for :header_tags do %>
    <%= javascript_include_tag 'budget_helper', 'budget_frontend', :plugin => 'redmine_budget' %>
<% end %>

app/views/budget/_issue_show.html.erb
<hr />
<table class="attributes redmine_budget_frontend" data-spent-time="<%= @issue.spent_time %>" data-budget="<%= @issue.budget %>" data-cost-per-hour="50">
	<tbody>
		<tr>
			<th class="burned">Burned:</th>
			<td class="burned"><%= @issue.spent_time %></td>
			<th class="score">Score:</th>
			<td class="score"><%= @issue.score %></td>
		</tr>
		<tr>
			<th class="profit">Profit:</th>
			<td class="profit"><%= @issue.profit %></td>
			<th class=""></th>
			<td class=""></td>
		</tr>
	</tbody>
</table>

app/views/budget/calculate.html.erb
<% if @result.key?(:estimated) %>
<h3><%= t('.summary') %></h3>
<h2><%= t('.log_time') %></h2>

<table border="1">
	<tr>
		<th><%= t('.user') %></th>
		<th><%= t('.avg_rate') %></th>
		<th><%= t('.time_sum') %></th>
		<th><%= t('.cost_sum') %></th>
	</tr>
<% @issue.time_entries_with_children.group_by(&:user_id).each do |user_id, time_entries| %>
	<tr>
    <td style="font-weight: bold;"><%= User.find(user_id).lastname %></td>
    <% @issue.count_costs(user_id, time_entries).each do |cost| %>
      <%= content_tag :td, cost %>
    <% end %>
  </tr>
<% end %>
</table>

<h2><%= t('.realized') %></h2>
<table border="1">
	<tr>
		<th><%= t('.est_time') %></th>
		<td><%= @result[:estimated].to_f.round(2) %></td>
	</tr>
	<tr>
		<th><%= t('.spent_time') %></th>
		<td><%= @result[:spent].to_f.round(2) %></td>
	</tr>
	<tr>
		<th><%= t('.budget') %></th>
		<td><%= @result[:budget].to_f.round(2) %></td>
	</tr>
	<tr>
		<th><%= t('.profit') %></th>
		<td><%= @result[:profit].to_f.round(2) %></td>
	</tr>
	<tr>
		<th><%= t('.provision') %></th>
		<td><%= @result[:provision].to_f.round(2) %></td>
	</tr>
</table>
<% else %>
<p><%= t('.disclaimer', id: params[:issue_id]) %></p>
<% end %>
<br />
<br />
<hr />

app/views/budget/calculator.html.erb
<% html_title l(:budget_title) %>

<% content_for :header_tags do %>
  <%= javascript_include_tag 'budget_helper','budget', :plugin => 'redmine_budget' %>
  <%= stylesheet_link_tag 'budget', :plugin => 'redmine_budget' %>
<% end %>

<div class="redmine_budget">
	<div>
		<h2>Ustawienia</h2>
		<form class="settings">
			<fieldset>
				<label>Koszt za godzinę: </label><input type="text" name="cost_per_hour" value="50" /><br />
				<label>Stawka za godzinę: </label><input type="text" name="rate" disabled="disabled" /><br />
			</fieldset>
		</form>
	</div>
	<div class="splitcontentleft">
		<h2>Przelicz budżet na czas</h2>
		<form class="budget_calculator down">
			<fieldset>
				<label>Budżet: </label><input type="text" name="budget" /><br />
				<label>Przepalone godziny: </label><input type="text" name="burned" /><br />
				<label>Dostępne godziny: </label><input type="text" name="available" disabled="disabled" /><br />
				<label>Koszt: </label><input type="text" name="cost" disabled="disabled" /><br />
				<label>Overhead: </label><input type="text" name="overhead" disabled="disabled" /><br />
				<label>Acc Cost: </label><input type="text" name="acc_cost" disabled="disabled" /><br />
				<label>Zysk: </label><input type="text" name="profit" disabled="disabled" /><br />
				<label>Score: </label><input type="text" name="score" disabled="disabled" /><br />
				<div class="score-indicator"><div style="width:50%;"></div></div>
			</fieldset>
		</form>
	</div>

	<div class="splitcontentright">
		<h2>Przelicz czas na budżet</h2>
		<form class="time_calculator up">
			<fieldset>
				<label>Ilość godzin: </label><input type="text" name="hours" value="1" /><br />
				<label>Wymagany budżet: </label><input type="text" name="required_budget" disabled="disabled" /><br />
			</fieldset>
		</form>
	</div>
</div>

app/views/budget/index.html.erb
<% html_title t('budget_title') %>

<% content_for :header_tags do %>
  <%= javascript_include_tag 'jquery-throttle.min.js', 'budget_helper', 'budget', :plugin => 'redmine_budget' %>
  <%= stylesheet_link_tag 'budget', :plugin => 'redmine_budget' %>
  <style type="text/css">
    table.list td {
      border-top: 1px solid #e6eaef;
    }
    input[type='number'] {
      border: 1px solid #e6eaef;
    }
  </style>
<% end %>

<div class="redmine_budget" data-budget-calculate-path="<%= budget_calculate_path %>">
	<div class="budget_estimation" data-est-budget="<%= @issue.try(:budget) %>">
		<h2><%= t('.budget_estimation') %></h2>
		<h3><%= t('.work_time') %></h3>
		<table class="list estimation">
			<tr class="header">
				<th><%= t('.hours') %></th>
				<th><%= t('.rate') %></th>
				<th><%= t('.work_cost') %></th>
				<th><%= t('.lower_bid') %></th>
				<th><%= t('.middle_bid') %></th>
				<th><%= t('.upper_bid') %></th>
				<th></th>
			</tr>
			<tr class="row">
				<td><input type="number" name="estimation[][hours]" value=""></td>
				<td><input type="number" name="estimation[][rate]" value="<%= @settings[:default_rate] %>"></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td><a href="javascript: void(0);" class="remove">&times;</a></td>
			</tr>
		</table>
		<h3><%= t('.add_cost') %></h3>
		<table class="list additionals">
			<tr class="header">
				<th><%= t('.cost_name') %></th>
				<th><%= t('.cost_cost') %></th>
				<th></th>
			</tr>
			<tr class="row">
				<td><input type="text" name="additionals[][name]" value=""></td>
				<td><input type="number" name="additionals[][cost]" value=""></td>
				<td><a href="javascript: void(0);" class="remove">&times;</a></td>
			</tr>
		</table>
		<h3><%= t('.summary') %></h3>
		<table class="list summary">
			<tr>
				<th><%= t('.work_cost') %></th>
				<td></td>
			</tr>
			<tr>
				<th><%= t('.lower_bid') %></th>
				<td></td>
			</tr>
			<tr>
				<th><%= t('.middle_bid') %></th>
				<td></td>
			</tr>
			<tr>
				<th><%= t('.upper_bid') %></th>
				<td></td>
			</tr>
		</table>
	</div>
</div>

app/views/budget/issues.html.erb
<% html_title t('budget_title') %>

<% content_for :header_tags do %>
  <%= javascript_include_tag 'jquery-throttle.min.js', 'budget_helper', 'budget_issues', :plugin => 'redmine_budget' %>
  <%= stylesheet_link_tag 'budget', :plugin => 'redmine_budget' %>
<% end %>

<%= render partial: 'filter' %>

<div class="redmine_budget">
  <div class="issue_control">
    <h2><%= t('.budget_issues') %></h2>

    <table class="list estimation">
      <tr class="header">
        <th><%= t('.issue') %></th>
        <th><%= t('.budget') %></th>
        <th><%= t('.work_cost') %></th>
        <th><%= t('.add_cost') %></th>
        <th><%= t('.time_burned') %></th>
        <th><%= t('.score') %></th>
        <th><%= t('.profit') %></th>
        <th><%= t('.project') %></th>
        <th><%= t('.category') %></th>
        <th><%= t('.assignee') %></th>
      </tr>
      <% @issues.each do |issue| %>
      <tr class="row">
        <td><%= link_to "#{issue_link(issue)}", issue_path(id: issue.id), target: '_blank' %></td>
        <td><%= issue.budget %></td>
        <td><%= issue.work_cost %></td>
        <td><%= issue.add_cost %></td>
        <td><%= issue.spent_hours_with_children.to_f.round(2) %></td>
        <td><%= issue.budget_score %> %</td>
        <td><%= issue.budget_profit %></td>
        <td><%= issue.project.name %></td>
        <td><%= issue.category.try(:name) %></td>
        <td><%= issue.assigned_to %></td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/budget/user.html.erb
<% html_title l(:budget_title) %>

<% content_for :header_tags do %>
  <%= javascript_include_tag 'jquery-throttle.min.js', 'budget_helper', 'budget', :plugin => 'redmine_budget' %>
  <%= stylesheet_link_tag 'budget', :plugin => 'redmine_budget' %>
<% end %>

<form accept-charset="UTF-8" action="/issues" id="query_form" method="get">
  <fieldset id="filters" class="collapsible ">
    <legend onclick="toggleFieldset(this);" class="fa fa-minus-square">Filters</legend>

    <div style="">
      <table>
        <tbody>
          <tr>
            <td><label for="group_by">Group results by</label></td>
            <td>
              <select id="group_by" name="group_by">
                <option value="">&nbsp;</option>
                <option value="project">Project</option>
                <option value="tracker">Tracker</option>
                <option value="status">Status</option>
                <option value="priority">Priority</option>
                <option value="author">Author</option>
                <option value="assigned_to">Assignee</option>
                <option value="category">Category</option>
                <option value="fixed_version">Target version</option>
                <option value="done_ratio">% Done</option>
              </select>
            </td>
          </tr>

          <tr>
            <td>Show</td>
            <td><label class="inline"><input name="c[]" type="checkbox" value="description"> Description</label></td>
          </tr>
        </tbody>
      </table>
    </div>
  </fieldset>
    <p class="buttons hide-when-print">
      <a class="icon icon-checked fa fa-check" href="#" onclick="submit_query_form(&quot;query_form&quot;); return false;">Apply</a>
      <a href="/?set_filter=1" class="icon fa fa-times">Clear</a>
      <a class="icon icon-save fa fa-floppy-o" href="#" onclick="$('#query_form').attr('action', '/queries/new'); submit_query_form('query_form'); return false;">Save</a>
    </p>
</form>

<div class="redmine_budget">
  <div class="issue_control">
    <h2>Raport uzytkownika</h2>

    <table border="1" class="estimation">
      <tr class="header">
        <th>Zadanie</th>
        <th>Budget</th>
        <th>Koszty pracy</th>
        <th>Time Burned</th>
        <th>Score</th>
        <th>Profit</th>
      </tr>
      <% @issues.each do |issue| %>
      <tr class="row">
        <td><%= link_to "#{issue_link(issue)}", "#{budget_path}?issue_id=#{issue.id}", target: '_blank' %></td>
        <td><%= issue.budget %></td>
        <td><%= issue.work_cost %></td>
        <td><%= issue.spent_hours_with_children.to_f.round(2) %></td>
        <td><%= issue.budget_score %> %</td>
        <td><%= issue.budget_profit %></td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/redmine_budget/_settings.html.erb
<table class="budget-plugin">
  <tbody>
    <tr class="budget-tracker">
      <th><%= l(:tracker) %></th>
      <td>
        <%= select_tag "settings[tracker_id]", options_from_collection_for_select(Tracker.all, :id, :name, settings[:tracker_id]) %>
      </td>
    </tr>
    <tr class="budget-managers-group">
      <th><%= l(:managers_group) %></th>
      <td>
        <%= select_tag "settings[managers_id]", options_from_collection_for_select(Group.all, :id, :name, settings[:managers_id]) %>
      </td>
    </tr>
    <tr class="budget-access-group">
      <th><%= l(:access_group) %></th>
      <td>
        <%= select_tag "settings[access_id]", options_from_collection_for_select(Group.all, :id, :name, settings[:access_id]) %>
      </td>
    </tr>
    <tr class="budget-rate_factor">
      <th><%= l(:rate_factor) %></th>
      <td>
        <%= text_field_tag "settings[rate_factor]", settings[:rate_factor] %>
      </td>
    </tr>
    <tr class="budget-cost_factor">
      <th><%= l(:cost_factor) %></th>
      <td>
        <%= text_field_tag "settings[cost_factor]", settings[:cost_factor] %>
      </td>
    </tr>
    <tr class="budget-default_rate">
      <th><%= l(:default_rate) %></th>
      <td>
        <%= text_field_tag "settings[default_rate]", settings[:default_rate] %>
      </td>
    </tr>
    <tr class="budget-profit_share">
      <th><%= l(:profit_share) %></th>
      <td>
        <%= text_field_tag "settings[profit_share]", settings[:profit_share] %>
      </td>
    </tr>
    <tr class="budget-margin">
      <th><%= l(:margin) %></th>
      <td>
        <%= text_field_tag "settings[margin]", settings[:margin] %>
      </td>
    </tr>
    <tr class="budget-provision">
      <th><%= l(:provision) %></th>
      <td>
        <%= text_field_tag "settings[provision]", settings[:provision] %>
      </td>
    </tr>
  </tbody>
</table>